### PR TITLE
Code Improvements

### PR DESCRIPTION
**Pull request by fireflycons**
Hi perplexityjeff

Love this. Found it while looking for something similar to Android's DNS 66 for Windows DNS.

I've made a few improvements, such as better detection of the zones to clean up, and also addition of a `-Remove` command line argument to permit complete removal of all the blacklist entries.

Since I have an Active Directory integrated DNS, I will in time further enhance this to make the blacklist entries AD integrated such that they can be applied to one DNS server and be replicated to the others in the domain.

### CODE REVIEW

**Comment by perplexityjeff** [comment]
Hi Firefly, Thank you for the hard work on making it better. It looks great so I'll merge it with the base. 

I'll try and learn from your improvements as well!

Happy Holidays!

Jeff

**Comment by fireflycons** [comment]
Much appreciated :-)

Have already has some success with Active Directory integrating the DNS records.
Tell me, do you wish to support Windows versions earlier than 2012 now? From Server 2012 onward, the changes can be done entirely with PowerShell cmdlets, which is somewhat safer than modifying the registry directly, and it can be done without stopping the DNS service.

**Comment by perplexityjeff** [comment]
I think compatibility is still nice. I agree with you that it is safer however I think it is one of the strengths of the project that it does not really matter what OS you run it on. 

Do you suggest to remove 2008 support ? Maybe we can do something with switching what version you run or split them? I dont know, looking forward to your feedback.

**Comment by fireflycons** [comment]
Only that 2008 is end of life next month so there should be very few people still on it
https://support.microsoft.com/en-gb/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2

**Comment by fireflycons** [comment]
Either way I'll leave that in,  but use the powershell cmdlets if they are present

**Pull request merged**
